apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk = 36

    defaultConfig {
        minSdk = 24
        targetSdk = 36
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }

    namespace = 'ceui.pixiv.safe'

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    api libs.okhttp
    implementation libs.gson
    implementation libs.mmkv

    testImplementation libs.junit4
    testImplementation libs.mockWebServer
}
