package ceui.pixiv.db

object RecordType {
    const val VIEW_ILLUST_HISTORY = 1
    const val VIEW_NOVEL_HISTORY = 2
    const val VIEW_USER_HISTORY = 3

    const val BLOCK_ILLUST = 4
    const val BLOCK_NOVEL = 5
    const val BLOCK_USER = 6

    const val FAVORITE_USER = 7

    const val PAGING_DATA_HOME_DISCOVER_RECOMMEND_ILLUST = 100
    const val PAGING_DATA_HOME_DISCOVER_RECOMMEND_MANGA = 101
    const val PAGING_DATA_HOME_DISCOVER_RECOMMEND_NOVEL = 102

    const val PAGING_DATA_HOME_PUBLIC_FOLLOWING_ILLUST = 103
    const val PAGING_DATA_HOME_PRIVATE_FOLLOWING_ILLUST = 104

    const val PAGING_DATA_HOME_TRENDING_TAG_ILLUST = 105
    const val PAGING_DATA_HOME_TRENDING_TAG_NOVEL = 106

    const val PAGING_DATA_HOME_RECMMEND_USER = 107
    const val PAGING_DATA_BOOKMARKED_ILLUST_PUBLIC = 108
    const val PAGING_DATA_BOOKMARKED_ILLUST_PRIVATE = 109


    const val PAGING_DATA_ARTICLE_ALL = 110

    const val PAGING_DATA_ILLUST_RANKING = 10000


    const val USER_TASK = 1000_000
}