/* Standalone interaction prototype. All task/reward data stays in this browser. */
'use strict';
const $ = (selector) => document.querySelector(selector);
const icon = (name) => `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const escapeHTML = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DAY = 86400000;
const STORAGE_KEY = 'pixshaft-referral-prototype-v2';
const tasks = [
  {id:'invite', title:'邀请首位好友', category:'好友邀请', tag:'7 天 PRO', days:7, icon:'user', color:'lime', description:'好友安装并完成使用要求后，双方各获 7 天 PRO。', target:1, caption:'完成使用要求的好友', steps:['把 Pixiv-Shaft 专属邀请入口分享给一位还没用过 App 的朋友。','好友安装 App、登录并主动绑定邀请，在 7 天内于两个不同自然日使用核心功能；至少完成一次收藏。','系统验证通过后，你与好友各获得一张 7 天体验卡。'], condition:'仅限首次有效邀请。好友无需付费；每位新用户只能绑定一位邀请人。仅复制链接或下载未使用不算完成。'},
  {id:'recommend', title:'发布 App 推荐帖', category:'内容推荐', tag:'7 天 PRO', days:7, icon:'stack', color:'', description:'发布使用体验，附 App 截图和下载入口。审核通过可获 7 天 PRO。', target:1, caption:'App 推荐帖审核', steps:['在允许推广的社交平台或公开社区，发布一篇 Pixiv-Shaft App 推荐帖。','包含 App 名称、至少 100 字真实使用体验、1 张 App 功能截图，以及官方下载安装入口或专属邀请入口。','说明参与推荐活动可获得体验卡，提交帖子公开链接。审核通过即可领取，无点赞或粉丝数门槛。'], condition:'审核重点是 App 介绍是否真实、下载入口是否有效、推荐帖是否原创且公开可访问。可用官方产品素材配合个人体验；预计 2 个工作日内反馈。'},
  {id:'tutorial', title:'发布 App 使用教程', category:'使用教程', tag:'30 天 PRO', days:30, icon:'play', color:'peach', description:'以图文或视频介绍安装与操作步骤。审核通过可获 30 天 PRO。', target:1, caption:'App 教程审核', steps:['介绍 Pixiv-Shaft 的适用场景、下载安装步骤，以及一项核心功能的操作过程。','发布原创图文（至少 300 字与 3 张 App 操作截图），或不少于 60 秒的 App 实操视频。','附官方下载安装入口或专属邀请入口，说明活动奖励关系，提交公开链接等待审核。'], condition:'不限平台，不要求正面评价或点赞数。教程必须真实可复现，与 App 推荐帖任务不得使用同一份内容。预计 2 个工作日内反馈。'},
  {id:'circle', title:'邀请 3 位活跃好友', category:'持续使用', tag:'30 天 PRO', days:30, icon:'heart', color:'blue', description:'3 位新用户均达到持续活跃要求后，可获 30 天 PRO。', target:3, caption:'好友达成持续活跃', steps:['通过专属邀请入口，邀请 3 位不同的新用户安装 App 并完成有效体验。','每位好友在加入后的前 14 天内，至少 3 个不同自然日使用核心功能，且有 1 天发生在第 8–14 天。','3 位好友均达标后，领取一张 30 天 PRO 体验卡。'], condition:'首位有效邀请可计入本任务，但需额外满足持续活跃条件。本期仅可完成一次。'}
];
function freshState(){return {version:2, theme:'light', accent:'violet', effective:1, retained:0, status:{invite:'ready',recommend:'new',tutorial:'new',circle:'progress'}, submissions:{}, wallet:[], activeUntil:0};}
let state = freshState();
try {const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)); if(saved?.version===2 && Array.isArray(saved.wallet) && tasks.every(t => ['new','progress','pending','rejected','ready','claimed'].includes(saved.status?.[t.id]))) state={...state,...saved};} catch {}
let currentView='tasks', currentFilter='all', toastTimer, lastTrigger;
const sheet=$('#sheet');
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{}}
function applyTheme(){document.documentElement.dataset.theme=state.theme;document.documentElement.dataset.accent=state.accent;$('[data-action="theme"]').setAttribute('aria-label',state.theme==='dark'?'切换浅色模式':'切换深色模式');$('meta[name="theme-color"]').content=state.theme==='dark'?'#101014':'#f8f7fc';}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function openSheet(html){if(!sheet.open)lastTrigger=document.activeElement;$('#sheet-content').innerHTML=html;if(!sheet.open)sheet.showModal();sheet.scrollTop=0;}
function closeSheet(){sheet.close();}
sheet.addEventListener('close',()=>{if(lastTrigger?.isConnected)lastTrigger.focus();});
sheet.addEventListener('click',event=>{if(event.target===sheet){const r=sheet.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeSheet();}});
const statusText={new:'未开始',progress:'进行中',pending:'审核中',rejected:'需补充',ready:'可领取',claimed:'已领取'};
const ctaText={new:'查看任务',progress:'查看进度',pending:'查看审核',rejected:'补充内容',ready:'领取奖励',claimed:'查看奖励'};
function taskProgress(task){if(task.id==='invite')return Math.min(state.effective,1);if(task.id==='circle')return Math.min(state.retained,3);return ['ready','claimed'].includes(state.status[task.id])?1:0;}
function render(){
  applyTheme();
  const ready=tasks.filter(t=>state.status[t.id]==='ready').length;
  $('#earned-days').textContent=state.wallet.reduce((sum,c)=>sum+c.days,0);
  $('#invited-count').textContent=state.effective;
  const unused=state.wallet.filter(c=>!c.activatedAt&&c.expiresAt>Date.now()).length;
  $('#wallet-count').textContent=unused;$('#mobile-wallet-count').textContent=unused;$('#claimable-count').textContent=ready;$('#ready-count').textContent=ready;
  document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view===currentView;button.classList.toggle('selected',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});
  $('.tabs').hidden=currentView==='wallet';$('#task-list').hidden=currentView==='wallet';$('#wallet-list').hidden=currentView!=='wallet';$('.season').textContent=currentView==='wallet'?'自主激活 · 不自动续费':'每项限领一次';
  $('#section-title').innerHTML=currentView==='wallet'?`我的卡包 <span>${String(state.wallet.length).padStart(2,'0')}</span>`:'推荐任务 <span>04</span>';
  $('#section-subtitle').textContent=currentView==='wallet'?'查看已领取的体验卡及激活状态。':'查看任务要求与完成进度。';
  document.querySelectorAll('[data-filter]').forEach(button=>{const selected=button.dataset.filter===currentFilter;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;});
  $('#task-list').setAttribute('aria-labelledby',`tab-${currentFilter}`);
  const visible=tasks.filter(t=>currentFilter==='all'||(currentFilter==='ready'?state.status[t.id]==='ready':['progress','pending','rejected'].includes(state.status[t.id])));
  $('#task-list').innerHTML=visible.length?visible.map((task,index)=>{
    const status=state.status[task.id], progress=taskProgress(task);
    const caption=status==='pending'?'已提交，等待审核':status==='rejected'?'请补充 App 下载入口与说明':status==='claimed'?'奖励已存入卡包':task.caption;
    return `<article class="task-card ${status==='ready'?'claimable':''}" style="animation-delay:${index*35}ms"><div class="task-top"><div class="task-icon ${task.color}">${icon(task.icon)}</div><div class="task-copy"><div class="task-meta"><span>${task.category}</span><span>·</span><span class="state ${status==='ready'?'ready':''}">${statusText[status]}</span></div><h3>${task.title}</h3><p>${task.description}</p></div><div class="reward-pill"><b>${task.days}</b><span>天</span><span class="pro-label">PRO</span></div></div><div class="task-bottom"><div class="progress-area"><div class="progress-caption"><span>${caption}</span><b>${progress}/${task.target}</b></div><div class="progress-track" role="progressbar" aria-label="${task.caption}" aria-valuemin="0" aria-valuemax="${task.target}" aria-valuenow="${progress}"><span style="width:${progress/task.target*100}%"></span></div></div><button class="task-cta" data-task="${task.id}" aria-label="${ctaText[status]}：${task.title}">${ctaText[status]} ${icon(status==='ready'?'ticket':status==='claimed'?'check':'arrow')}</button></div></article>`;
  }).join(''):`<div class="empty-state">${icon('spark')}<h3>${currentFilter==='ready'?'暂无可领取奖励':'暂无进行中的任务'}</h3><p>${currentFilter==='ready'?'任务完成并通过验证后，可在此领取。':'在全部任务中查看参与条件。'}</p><button class="primary" data-filter="all">查看全部任务</button></div>`;
  renderWallet();persist();
}
function dateText(time){return new Date(time).toLocaleDateString('zh-CN',{year:'numeric',month:'numeric',day:'numeric'});}
function dateTimeText(time){return new Date(time).toLocaleString('zh-CN',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});}
function renderWallet(){
  const active=state.activeUntil>Date.now()?`<div class="note-box">当前 PRO 体验至 ${dateTimeText(state.activeUntil)}。激活新卡将从此时间顺延。</div>`:'';
  $('#wallet-list').innerHTML=state.wallet.length?active+state.wallet.map(card=>{
    const expired=!card.activatedAt&&card.expiresAt<=Date.now();
    return `<article class="wallet-card"><div class="wallet-card-top"><h3>PRO ${card.days} 天体验卡</h3><div class="reward-pill"><b>${card.days}</b> 天</div></div><p>来自「${tasks.find(t=>t.id===card.taskId)?.title||'推荐任务'}」</p><p>${card.activatedAt?`已于 ${dateText(card.activatedAt)} 激活 · 权益已顺延`:expired?'已过激活期限':`请于 ${dateTimeText(card.expiresAt)} 前激活`}</p>${card.activatedAt||expired?`<span class="eyebrow">${expired?'已过期':'已激活'}</span>`:`<button class="primary" data-activate="${card.id}">激活 ${card.days} 天 PRO ${icon('arrow')}</button>`}</article>`;
  }).join(''):`<div class="empty-state">${icon('ticket')}<h3>暂无体验卡</h3><p>完成任务后，可在任务页领取。<br>领取后 30 天内激活。</p><button class="primary" data-view="tasks">查看任务 ${icon('arrow')}</button></div>`;
}
function setView(view){currentView=view;render();if(sheet.open)closeSheet();$('.task-section').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
function showTask(id){
  const task=tasks.find(t=>t.id===id);if(!task)return;
  const status=state.status[id];
  if(status==='claimed'){setView('wallet');return;}
  if(status==='ready'){showClaim(id);return;}
  const progress=id==='circle'?`<div class="note-box">已有效邀请 ${state.effective} 人，其中 ${state.retained} / 3 人达成持续活跃。仅展示汇总状态，保护好友隐私。</div>`:'';
  const review=status==='pending'?'<div class="note-box">内容已提交，预计 2 个工作日内反馈。通过后即可领取；若需补充，会展示具体原因。原型中可在「演示控制台」模拟审核结果。</div>':status==='rejected'?'<div class="note-box">需补充：请明确标注 Pixiv-Shaft 名称，补充有效的 App 下载安装入口与活动奖励说明。补充后可重新提交。</div>':'';
  openSheet(`<div class="eyebrow">${task.category} · ${task.tag}</div><h2 id="sheet-title">${task.title}</h2><div class="detail-reward"><strong>${task.days}<small> 天</small></strong><div><b>PRO 体验卡</b><p>完成后领取，30 天内自主激活</p></div></div>${progress}${review}<h3>完成条件</h3><ol class="detail-steps">${task.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="note-box">${task.condition}</div>${['recommend','tutorial'].includes(id)?status==='pending'?'<button class="sheet-secondary" data-action="close">知道了</button>':`<button class="primary" data-submit-form="${id}">${status==='rejected'?'补充并重新提交':'提交内容链接'} ${icon('arrow')}</button>`:`<button class="primary" data-action="invite">邀请好友 ${icon('arrow')}</button>`}`);
}
function showClaim(id){const task=tasks.find(t=>t.id===id);openSheet(`<div class="celebration"><div class="success-shape">${icon('check')}</div><div class="eyebrow">EXPERIENCE PASS</div><h2 id="sheet-title">任务已完成</h2><p class="lead">「${task.title}」已完成<br>可领取 ${task.days} 天 PRO 体验卡。</p></div><div class="detail-reward"><strong>${task.days}<small> 天</small></strong><div><b>PRO ${task.days} 天体验卡</b><p>激活后开始计时 · 不自动续费</p></div></div><button class="primary" data-claim="${id}">领取体验卡 ${icon('ticket')}</button><p style="text-align:center;margin-top:12px;font-size:10px">领取后 30 天内激活，可顺延现有体验权益。</p>`);}
function claim(id){if(state.status[id]!=='ready')return;const task=tasks.find(t=>t.id===id);state.status[id]='claimed';state.wallet.push({id:`${id}-${Date.now()}`,taskId:id,days:task.days,claimedAt:Date.now(),expiresAt:Date.now()+30*DAY,activatedAt:0});render();openSheet(`<div class="celebration"><div class="success-shape">${icon('ticket')}</div><div class="eyebrow">REWARD CLAIMED</div><h2 id="sheet-title">已存入卡包</h2><p class="lead">${task.days} 天 PRO 体验卡已领取。<br>激活期限：${dateTimeText(state.wallet.at(-1).expiresAt)}</p></div><button class="primary" data-view="wallet">查看卡包 ${icon('arrow')}</button><button class="sheet-secondary" data-action="close">返回任务</button>`);}
function showActivate(id){const card=state.wallet.find(c=>c.id===id);if(!card||card.activatedAt)return;if(card.expiresAt<=Date.now()){render();return toast('这张卡已过激活期限');}const end=Math.max(Date.now(),state.activeUntil)+card.days*DAY;openSheet(`<div class="eyebrow">ACTIVATE PRO</div><h2 id="sheet-title">激活 ${card.days} 天 PRO</h2><p class="lead">${state.activeUntil>Date.now()?'你已有体验权益，新卡会从当前结束时间顺延。':'激活后开始计时。'}<br>预计体验至 ${dateTimeText(end)}。</p><div class="note-box">本原型只演示权益状态，不会更改真实账号。正式版激活需服务端确认；体验卡不自动续费。</div><button class="primary" data-confirm-activate="${card.id}">确认激活 ${icon('spark')}</button><button class="sheet-secondary" data-action="close">暂不激活</button>`);}
function activate(id){const card=state.wallet.find(c=>c.id===id);if(!card||card.activatedAt)return;if(card.expiresAt<=Date.now()){closeSheet();render();return toast('这张卡已过激活期限');}card.activatedAt=Date.now();state.activeUntil=Math.max(Date.now(),state.activeUntil)+card.days*DAY;render();openSheet(`<div class="celebration"><div class="success-shape">${icon('spark')}</div><h2 id="sheet-title">已激活</h2><p class="lead">${card.days} 天 PRO 体验已激活（演示）。<br>体验至 ${dateTimeText(state.activeUntil)}。</p></div><button class="primary" data-action="close">完成 ${icon('arrow')}</button>`);}
function showInvite(){openSheet(`<div class="eyebrow">INVITE A FRIEND</div><h2 id="sheet-title">邀请好友使用 Pixiv-Shaft</h2><p class="lead">首次邀请达标后，双方各获 7 天 PRO。<br>好友需为新用户，无需付费。</p><div class="detail-reward">${icon('user')}<div><b>双方各获 7 天 PRO</b><p>新用户在 7 天内使用 2 天，并完成一次收藏</p></div></div><div class="link-box"><b>示例邀请码</b>SHAFT-C7K2</div><div class="note-box">邀请功能暂未开放。以下文案仅供预览，分享不会计入奖励。</div><button class="primary" data-action="copy-invite">复制邀请文案 ${icon('copy')}</button><button class="sheet-secondary" data-action="invite-progress">查看邀请进度</button>`);}
async function copy(textValue){try{await navigator.clipboard.writeText(textValue);const old=$('#copy-status');if(old)old.remove();if(sheet.open){const status=document.createElement('p');status.id='copy-status';status.role='status';status.textContent='文案已复制';status.style.cssText='text-align:center;margin-top:12px;color:var(--primary)';$('#sheet-content').append(status);}else toast('文案已复制');}catch{const box=document.createElement('textarea');box.value=textValue;box.readOnly=true;box.setAttribute('aria-label','可手动复制的文案');box.style.cssText='width:100%;min-height:120px;margin-top:18px';(sheet.open?$('#sheet-content'):document.body).append(box);box.select();if(!sheet.open)toast('无法自动复制，请手动选择复制');}}
function showForm(id){const task=tasks.find(t=>t.id===id);const previous=state.submissions[id]||{};openSheet(`<div class="eyebrow">${task.category} · PRO ${task.days} 天</div><h2 id="sheet-title">提交推荐内容</h2><p class="lead">请提供公开链接和内容说明。预计 2 个工作日内完成审核。</p><form id="submission-form" data-id="${id}"><label class="form-field">内容链接<input name="url" type="url" required placeholder="https://…" value="${escapeHTML(previous.url||'')}" maxlength="2000"></label><label class="form-field">内容说明<textarea name="description" required minlength="20" maxlength="1000" placeholder="填写发布平台、介绍的功能及下载入口位置，至少 20 字">${escapeHTML(previous.description||'')}</textarea></label><label style="display:flex;gap:9px;margin-top:18px;font-size:11px;line-height:1.8;color:var(--muted)"><input name="original" type="checkbox" required style="accent-color:var(--primary)">内容为本人原创，已附 App 下载入口，并注明参与活动可获体验卡。</label><p id="form-error" class="form-error" role="alert"></p><button class="primary" type="submit">提交审核 ${icon('arrow')}</button></form>`);}
document.addEventListener('submit',event=>{if(event.target.id!=='submission-form')return;event.preventDefault();const form=event.target, id=form.dataset.id;let url;try{url=new URL(form.elements.url.value.trim());if(!['https:','http:'].includes(url.protocol)||!url.hostname.includes('.')||url.username||url.password)throw Error();}catch{$('#form-error').textContent='请填写完整、可公开访问的 HTTP 或 HTTPS 推广链接。';return;}const description=form.elements.description.value.trim();if(description.length<20){$('#form-error').textContent='请至少填写 20 字内容介绍。';return;}state.submissions[id]={url:url.href,description,submittedAt:Date.now()};state.status[id]='pending';render();openSheet(`<div class="celebration"><div class="success-shape">${icon('check')}</div><h2 id="sheet-title">已提交</h2><p class="lead">预计 2 个工作日内反馈，审核通过后即可领取。<br>原型可在页尾「演示控制台」模拟审核。</p></div><button class="primary" data-action="close">返回任务中心</button>`);});
function showRules(){openSheet(`<div class="eyebrow">PROGRAM RULES</div><h2 id="sheet-title">活动规则</h2><p class="lead">以下为提议的运营规则，供设计评审确认；原型中的数据和权益均为演示。</p><ul class="rules-list"><li><strong>体验时长</strong>一周卡为 7 × 24 小时，一个月卡统一为 30 × 24 小时。卡片领取后 30 天内激活；过期不自动激活。已激活卡不可转赠。</li><li><strong>领取次数</strong>首位好友安装并完成有效体验，奖励 7 天；App 推荐帖奖励 7 天；App 上手教程奖励 30 天；3 位好友持续活跃奖励 30 天。本期邀请人最多获 74 天；每位受邀新用户另获一次 7 天。首位好友可计入持续活跃任务，同一份 App 推荐内容不可重复提交。</li><li><strong>有效邀请条件</strong>新用户安装 App、登录并主动确认绑定唯一邀请人；7 天内在两个不同自然日使用核心功能，且至少收藏一次。持续活跃任务还需前 14 天内活跃 3 天，其中 1 天在第 8–14 天。</li><li><strong>领取与激活</strong>任务达标后卡片进入可领取状态。激活时顺延已有同档 PRO 权益，不覆盖已付费天数；更高档会员须待可用时激活，细则正式接入时确认。不自动续费。</li><li><strong>审核与补充</strong>内容任务预计 2 个工作日内反馈；展示未通过原因并支持重新提交。无需购买、不要求好评、不以点赞数判定。推荐内容需明确介绍 Pixiv-Shaft，并附有效的官方下载安装入口或专属邀请入口。</li><li><strong>公平参与</strong>禁止自邀、批量账号、重复内容与骚扰式发布。异常邀请人工复核并提供申诉入口，不仅凭共享网络拒绝。活动规则调整只影响后续参与，不追溯已达成的合法奖励。</li></ul><button class="primary" data-action="close">了解了</button>`);}
function showMaterials(){openSheet(`<div class="eyebrow">SHARE PIXIV-SHAFT</div><h2 id="sheet-title">推荐内容参考</h2><p class="lead">可参考以下结构，结合自己的使用体验撰写。发布时需附下载入口，并注明活动奖励。</p><div class="material-card"><h3>01 / App 推荐帖</h3><p>介绍一个用过的功能，附 App 截图、下载入口和活动说明。</p><button class="text-button" data-action="copy-promo">复制推荐帖提纲 ${icon('copy')}</button><button class="text-button" data-task="recommend">查看推荐帖任务 ${icon('arrow')}</button></div><div class="material-card"><h3>02 / 使用教程</h3><p>说明下载安装步骤，演示至少一项核心功能的操作过程。</p><button class="text-button" data-task="tutorial">查看 App 教程任务 ${icon('arrow')}</button></div><div class="material-card"><h3>03 / 好友邀请</h3><p>介绍 App 用途，附邀请入口与使用要求。</p><button class="text-button" data-action="invite">邀请好友 ${icon('arrow')}</button></div>`);}

function showDemo(){openSheet(`<div class="eyebrow">PROTOTYPE CONTROLS</div><h2 id="sheet-title">演示控制台</h2><p class="lead">仅改变本浏览器的示例数据，用于评审完整流程。不会发出邀请、提交审核或发放真实 PRO。</p><div class="demo-row"><div>有效邀请 ${state.effective} 人<small>新好友达到首次体验条件</small></div><button data-sim="invite">增加 1 人</button></div><div class="demo-row"><div>持续活跃 ${state.retained} / 3 人<small>不得超过有效邀请人数</small></div><button data-sim="retained" ${state.retained>=Math.min(state.effective,3)?'disabled':''}>达标 1 人</button></div>${tasks.filter(t=>['recommend','tutorial'].includes(t.id)).map(t=>`<div class="demo-row"><div>${t.title}<small>${statusText[state.status[t.id]]}</small></div><div style="display:flex;gap:5px"><button data-review="${t.id}:ready" ${state.status[t.id]!=='pending'?'disabled':''}>通过</button><button data-review="${t.id}:rejected" ${state.status[t.id]!=='pending'?'disabled':''}>需补充</button></div></div>`).join('')}<button class="sheet-secondary" data-action="reset-confirm">重置全部演示数据</button>`);}
document.addEventListener('click',event=>{
  const button=event.target.closest('button');if(!button||button.disabled)return;const d=button.dataset;
  if(d.view){setView(d.view);return;}
  if(d.filter){currentFilter=d.filter;render();document.querySelector(`[role="tab"][data-filter="${currentFilter}"]`)?.focus();return;}
  if(d.task){showTask(d.task);return;}if(d.claim){claim(d.claim);return;}if(d.activate){showActivate(d.activate);return;}if(d.confirmActivate){activate(d.confirmActivate);return;}if(d.submitForm){showForm(d.submitForm);return;}
  if(d.sim){if(d.sim==='invite'){state.effective++;if(state.status.invite!=='claimed')state.status.invite='ready';}else if(state.retained<Math.min(state.effective,3)){state.retained++;if(state.retained>=3&&state.status.circle!=='claimed')state.status.circle='ready';}render();showDemo();return;}
  if(d.review){const [id,status]=d.review.split(':');if(state.status[id]==='pending')state.status[id]=status;render();showDemo();return;}
  switch(d.action){
    case 'close':closeSheet();break;
    case 'theme':state.theme=state.theme==='light'?'dark':'light';applyTheme();persist();break;
    case 'palette':state.accent=['violet','rose','teal'][(['violet','rose','teal'].indexOf(state.accent)+1)%3];applyTheme();persist();toast('已切换主题配色');break;
    case 'rules':showRules();break;
    case 'invite':showInvite();break;
    case 'copy-invite':copy('Pixiv-Shaft 支持浏览插画、管理收藏。首次通过邀请完成使用要求，双方可各获 7 天 PRO。\n[示例文案，邀请活动暂未开放。]');break;
    case 'invite-progress':openSheet(`<div class="eyebrow">INVITATION STATUS</div><h2 id="sheet-title">邀请进度</h2><p class="lead">${state.effective} 人完成有效体验，${state.retained} 人达成持续活跃。<br>系统仅展示汇总进度，不公开好友的使用明细。</p><div class="note-box">首次有效邀请：${Math.min(state.effective,1)} / 1<br>3 位好友持续活跃：${state.retained} / 3<br>邀请进度由服务端验证；本页为演示数据。</div><button class="primary" data-action="invite">继续邀请 ${icon('arrow')}</button>`);break;
    case 'materials':showMaterials();break;
    case 'copy-promo':copy('Pixiv-Shaft 使用体验\n功能：[介绍实际使用过的功能]\n体验：[优点、不足和适用场景]\n截图：[添加 App 功能截图]\n下载：[填写官方下载或邀请入口]\n活动说明：参与 App 推荐计划，内容审核通过可获得 PRO 体验卡。\n[请补全后发布。当前活动尚未开放。]');break;
    case 'demo':showDemo();break;
    case 'reset-confirm':openSheet('<div class="eyebrow">RESET DEMO</div><h2 id="sheet-title">重置演示数据？</h2><p class="lead">清空本浏览器的演示推广记录、体验卡与激活记录，恢复初始示例任务。</p><button class="primary" data-action="reset">重置演示</button><button class="sheet-secondary" data-action="close">保留当前进度</button>');break;
    case 'reset':{const {theme,accent}=state;state={...freshState(),theme,accent};currentView='tasks';currentFilter='all';render();closeSheet();toast('已恢复初始演示数据');break;}
  }
});
$('.tabs').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const filters=['all','progress','ready'];let i=filters.indexOf(currentFilter);i=event.key==='Home'?0:event.key==='End'?2:(i+(event.key==='ArrowRight'?1:2))%3;currentFilter=filters[i];render();$(`#tab-${currentFilter}`).focus();});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});
render();
